#!/bin/bash

set -euo pipefail

env | sort

if [[ -z "$GITHUB_TOKEN" ]]; then
  echo "GITHUB_TOKEN needs to be set"
  exit 1
fi

echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
cat "${GITHUB_EVENT_PATH}"

action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")

echo "action=${action}"
